import type { ChecklistItemConfig } from '../engine/types/config';

/**
 * Documenten per type financier. Bewust generieke categorieën: LOFI noemt, rangschikt en
 * adviseert geen financiers.
 */
export const DOCUMENT_CHECKLIST: readonly ChecklistItemConfig[] = [
  {
    id: 'kvk_uittreksel',
    label: 'Uittreksel KvK',
    description: 'Niet ouder dan drie maanden.',
    required: true,
    financierTypes: 'alle',
    legalForms: 'alle',
    stage: 'alle',
  },
  {
    id: 'identiteitsbewijs',
    label: 'Geldig identiteitsbewijs van alle eigenaren',
    description: 'Houd het bij de hand; upload het alleen bij de financier zelf.',
    required: true,
    financierTypes: 'alle',
    legalForms: 'alle',
    stage: 'alle',
  },
  {
    id: 'ondernemingsplan',
    label: 'Ondernemingsplan',
    description: 'Je verhaal bij de cijfers. De toelichting uit stap 6 vormt de kern.',
    required: true,
    financierTypes: 'alle',
    legalForms: 'alle',
    stage: 'alle',
  },
  {
    id: 'cv',
    label: 'CV van de ondernemer(s)',
    description: 'Laat zien welke ervaring je meeneemt.',
    required: true,
    financierTypes: 'alle',
    legalForms: 'alle',
    stage: 'starter',
  },
  {
    id: 'jaarrekeningen',
    label: 'Jaarrekeningen van de laatste twee tot drie jaar',
    description: 'Inclusief balans en resultatenrekening.',
    required: true,
    financierTypes: ['bank', 'kredietunie', 'crowdfunding', 'microfinancier'],
    legalForms: 'alle',
    stage: 'bestaand',
  },
  {
    id: 'tussentijdse_cijfers',
    label: 'Tussentijdse cijfers van het lopende jaar',
    description: 'Tot en met de laatst afgesloten maand.',
    required: true,
    financierTypes: ['bank', 'kredietunie'],
    legalForms: 'alle',
    stage: 'bestaand',
  },
  {
    id: 'ib_aangiften',
    label: 'Aangiften inkomstenbelasting van de laatste twee jaar',
    description: 'Van alle eigenaren.',
    required: true,
    financierTypes: ['bank', 'microfinancier'],
    legalForms: ['eenmanszaak', 'vof'],
    stage: 'bestaand',
  },
  {
    id: 'bankafschriften',
    label: 'Bankafschriften van de zakelijke rekening',
    description: 'Meestal de laatste zes tot twaalf maanden.',
    required: true,
    financierTypes: ['bank', 'microfinancier', 'kredietunie'],
    legalForms: 'alle',
    stage: 'bestaand',
  },
  {
    id: 'offertes',
    label: 'Offertes bij de investeringen',
    description: 'Onderbouwt de bedragen in stap 2.',
    required: true,
    financierTypes: 'alle',
    legalForms: 'alle',
    stage: 'alle',
  },
  {
    id: 'overzicht_verplichtingen',
    label: 'Overzicht van lopende leningen en leaseverplichtingen',
    description: 'Saldo, rente, looptijd en maandbedrag per verplichting.',
    required: true,
    financierTypes: ['bank', 'kredietunie', 'leasemaatschappij'],
    legalForms: 'alle',
    stage: 'bestaand',
  },
  {
    id: 'prive_begroting',
    label: 'Privébegroting',
    description: 'Wat je per maand nodig hebt om van te leven; onderbouwt je privé-opnamen.',
    required: true,
    financierTypes: ['bank', 'microfinancier'],
    legalForms: ['eenmanszaak', 'vof'],
    stage: 'alle',
  },
  {
    id: 'statuten',
    label: 'Statuten en aandeelhoudersregister',
    description: 'Inclusief de structuur van eventuele holdings.',
    required: true,
    financierTypes: 'alle',
    legalForms: ['bv'],
    stage: 'alle',
  },
  {
    id: 'vof_contract',
    label: 'Vof-contract',
    description: 'Afspraken tussen de vennoten.',
    required: true,
    financierTypes: 'alle',
    legalForms: ['vof'],
    stage: 'alle',
  },
  {
    id: 'leningsovereenkomst_familie',
    label: 'Schriftelijke leningsovereenkomst',
    description: 'Bedrag, rente, looptijd en aflossing van de lening uit je netwerk.',
    required: true,
    financierTypes: ['familie_vrienden'],
    legalForms: 'alle',
    stage: 'alle',
  },
  {
    id: 'lease_specificatie',
    label: 'Specificatie van het leaseobject',
    description: 'Merk, type, bouwjaar en de offerte van de leverancier.',
    required: true,
    financierTypes: ['leasemaatschappij'],
    legalForms: 'alle',
    stage: 'alle',
  },
  {
    id: 'campagne_materiaal',
    label: 'Pitchtekst en beeldmateriaal',
    description: 'Voor de campagnepagina.',
    required: true,
    financierTypes: ['crowdfunding'],
    legalForms: 'alle',
    stage: 'alle',
  },
  {
    id: 'huurcontract',
    label: 'Huurcontract of intentieverklaring bedrijfsruimte',
    description: 'Alleen als je een pand huurt of gaat huren.',
    required: false,
    financierTypes: 'alle',
    legalForms: 'alle',
    stage: 'alle',
  },
  {
    id: 'debiteuren_crediteuren',
    label: 'Ouderdomsanalyse debiteuren en crediteuren',
    description: 'Laat zien hoe snel er betaald wordt.',
    required: false,
    financierTypes: ['bank', 'kredietunie'],
    legalForms: 'alle',
    stage: 'bestaand',
  },
  {
    id: 'intentieverklaringen',
    label: 'Intentieverklaringen of referenties van klanten',
    description: 'Maakt je omzetprognose geloofwaardiger.',
    required: false,
    financierTypes: ['microfinancier', 'kredietunie', 'crowdfunding'],
    legalForms: 'alle',
    stage: 'alle',
  },
  {
    id: 'verzekeringen',
    label: 'Overzicht van je verzekeringen',
    description: 'Denk aan aansprakelijkheid, inventaris en arbeidsongeschiktheid.',
    required: false,
    financierTypes: 'alle',
    legalForms: 'alle',
    stage: 'alle',
  },
];
